"""hermes-homeassistant — Home Assistant gateway platform + smart-home tools for Hermes Agent.

Formerly built into hermes-agent core (``plugins/platforms/homeassistant`` and
``tools/homeassistant_tool.py``). Everything a migrated install relies on is unchanged: platform name
``homeassistant``, toolset ``homeassistant``, tools ``ha_list_entities`` / ``ha_get_state`` /
``ha_list_services`` / ``ha_call_service``, env vars ``HASS_TOKEN`` / ``HASS_URL`` /
``HASS_HOME_CHANNEL`` and the ``platforms.homeassistant.extra`` config keys.

Wiring goes only through the public plugin API (``ctx.register_platform`` / ``ctx.register_tool``).
"""

from __future__ import annotations

import dataclasses
import importlib.machinery
import logging
from typing import Any, Dict

from gateway.platforms._shared import env_is_connected, seed_extra_from_env

from .adapter import HomeAssistantAdapter, _standalone_send, check_ha_requirements, validate_ha_config
from .tools import register_tools

logger = logging.getLogger(__name__)

PLATFORM_NAME = "homeassistant"

# PlatformEntry fields added to core alongside this plugin's extraction. Core used to hardcode these
# behaviours for Home Assistant; an older core does not know them (PlatformEntry raises TypeError on
# unknown keys), so they are only passed when the running core supports them.
_OPTIONAL_ENTRY_KWARGS: Dict[str, Any] = {
    # Inbound HA events are system-generated by the instance the adapter authenticated to with
    # HASS_TOKEN, so they bypass the user allowlist (core used to special-case HA for this).
    "trusted_inbound": True,
    # Event-driven notifications: minimal tool-progress display (core used to hardcode this tier).
    "display_tier": "minimal",
    # HASS_* is shared with this plugin's own tools: profile clones strip it only when the source
    # profile runs the adapter.
    "shared_env_prefixes": ("HASS_",),
}


def _env_enablement() -> dict:
    """Seed ``platforms.homeassistant.extra`` from env when enabled via HASS_TOKEN alone.

    ``HASS_URL`` -> ``extra["url"]``; ``HASS_HOME_CHANNEL`` (+ ``HASS_HOME_CHANNEL_NAME``) -> home channel
    used by cron ``deliver=homeassistant``.
    """
    return seed_extra_from_env([("HASS_URL", "url", None)], home_env="HASS_HOME_CHANNEL")


def _supported_entry_fields() -> set:
    from gateway.platform_registry import PlatformEntry
    return {f.name for f in dataclasses.fields(PlatformEntry)}


def _platform_kwargs() -> Dict[str, Any]:
    kwargs: Dict[str, Any] = dict(
        name=PLATFORM_NAME,
        label="Home Assistant",
        adapter_factory=HomeAssistantAdapter,
        check_fn=check_ha_requirements,  # passive: aiohttp importable
        validate_config=validate_ha_config,
        is_connected=env_is_connected("HASS_TOKEN"),
        required_env=["HASS_TOKEN"],
        install_hint="pip install aiohttp",
        standalone_sender_fn=_standalone_send,  # out-of-process cron delivery via notify.notify
        max_message_length=HomeAssistantAdapter.MAX_MESSAGE_LENGTH,
        emoji="🏠",
        allow_update_command=True,
        env_enablement_fn=_env_enablement,
        cron_deliver_env_var="HASS_HOME_CHANNEL",
    )
    supported = _supported_entry_fields()
    for key, value in _OPTIONAL_ENTRY_KWARGS.items():
        if key in supported:
            kwargs[key] = value
        else:
            logger.debug("homeassistant: core PlatformEntry has no %r field; not passing it", key)
    return kwargs


def _core_ships_home_assistant() -> bool:
    """True on a Hermes core that still bundles Home Assistant (``tools/homeassistant_tool.py``, removed
    together with ``plugins/platforms/homeassistant`` when core dropped it).

    Looks only inside the imported ``tools`` package's own ``__path__``: a plain ``find_spec`` also
    consults meta-path finders (e.g. an editable install of a different checkout) and can report a
    module the running core does not have."""
    try:
        import tools as core_tools
        search = list(getattr(core_tools, "__path__", None) or ())
        return bool(search) and importlib.machinery.PathFinder.find_spec(
            "tools.homeassistant_tool", search) is not None
    except ImportError:
        return False


def register(ctx) -> None:
    """Plugin entry point — called by the Hermes plugin loader."""
    if _core_ships_home_assistant():
        # Registering on top of the built-in would shadow core's ha_* tools and replace its adapter.
        logger.info("homeassistant: this Hermes core still ships Home Assistant built in; "
                    "the plugin stays inactive until core drops it")
        return
    ctx.register_platform(**_platform_kwargs())
    register_tools(ctx)


__all__ = ["register", "register_tools", "HomeAssistantAdapter"]
